### PR TITLE
implement FritzDect!4XX devices ...

### PR DESCRIPTION
**Pull request by SmokingDevices**
Hi, 

i tried to implement the new toy, but unfortunately iam not a xml-master.
I did not manage to find a way to define the code for using the buttons without wrapping a list around. I think this is not a solution but as i said iam unable to find a better way. So if you have an idea howto solve this issue please let me know and i will work this into the PR. 

Best, 
Jan

### CODE REVIEW

**Comment by kaklakariada** [comment]
Hi @SmokingDevices !
Thanks for your PR and for adding sample payloads!
The XML library we use supports inline lists (see http://simple.sourceforge.net/download/stream/doc/tutorial/tutorial.php#inline). I have not tried this out. If you don't succeed, I can have a look.

**Comment by SmokingDevices** [comment]
Hi @kaklakariada ,

thanks for this hint, i worked this in and now everything should be fine.
please review again.

Thx Jan

**Review by kaklakariada — APPROVED** [review]
Sorry for the delay. Looks good, thank you!

**Comment by kaklakariada** [comment]
I just published version 1.2.2 including your changes to jcenter: https://jcenter.bintray.com/com/github/kaklakariada/fritzbox-java-api/1.2.2/

**Pull request merged**
